### ISSUE TITLE
Firefox browser-to-browser replication doesn't work

### ISSUE THREAD

**Issue by karissa** [datproject/datfolder#138]
Webrtc servers have trouble reaching each other and we get some console errors.

<img width="1256" alt="screen shot 2016-07-12 at 3 22 36 pm" src="https://cloud.githubusercontent.com/assets/633012/16785757/999d6bde-4844-11e6-8278-f3edce474f10.png">

**Comment by clkao** [comment]
Note that the deployed version seems working, but I can reproduce this issue with current master

**Comment by juliangruber** [comment]
`localhost` has its own restrictions, can you try adding the line `127.0.1.1     dev` to `/etc/hosts` and try again on `http://dev:8080/` (use anything for `dev` you like)

**Comment by clkao** [comment]
From #142 you can do `TEST_SERVER=http://localhost:8080 npm run test:e2e:firefox` for now.  It fails because the number of peers is not updated.  But if I make the test pause longer and and drag some files in, I saw both windows eventually synced.

**Comment by karissa** [comment]
firefox seems to work for this now

**Comment by karissa** [comment]
This seems to be broken again on Firefox

**Comment by karissa** [comment]
Getting a 'no element found' error: <img width="1247" alt="screen shot 2017-01-02 at 4 08 43 pm" src="https://cloud.githubusercontent.com/assets/633012/21597842/d462a1ea-d105-11e6-9dfe-55de05692ac4.png">

**Comment by timdream** [comment]
@karissa What's the reproduce step to trigger that error? I can try to track down the problem and report it on Bugzilla@Mozilla.

**Comment by karissa** [comment]
1. Open a dev:8080
2. Click 'create new dat'
3. Open a new window (preferably a private window to emulate a separate computer)
4. Copy the link from window 1 (e.g., dev:8080/view/b3d) to window 2
5. You should see '1 Source'  as they connect to each other. Instead, you see this error. 

@mafintosh is this a known bug in firefox for webrtc-swarm?

**Comment by timdream** [comment]
Does not happen on the deployed version (for both Fx52 and Fx53). Will try to set up the dev environment when I have time to do that...

**Comment by karissa** [comment]
Looks like you're right, I don't see it on the deployed version. Maybe it has something to do with https: vs. http, since the deployed version is https

**Comment by karissa** [comment]
(and so is the signalhub)

**Comment by karissa** [comment]
I'll close this then (thanks for taking more looks @timdream). I also merged a PR to make sure the browser message doesn't show up for firefox for now https://github.com/datproject/datfolder/pull/351

**Comment by timdream** [comment]
@karissa On a unrelated note: what stops the dev environment from serving with HTTPS? Adding an exception should be just a click away right?
