### ISSUE TITLE
adding 'dotfiles' (`.`)

### ISSUE THREAD

**Issue by karissa** [datproject/datfolder#262]
When a user dragging in a folder with dotfiles, like `.git` or `.dat`, should we skip them?

**Comment by laurengarcia** [comment]
i think @joehand just filed this against dat-cli too https://github.com/datproject/dat/issues/521

**Comment by joehand** [comment]
I think we have to skip `.dat` folders otherwise you get weird behavior if someone synced a dat.land dat via desktop/CLI.

**Comment by karissa** [comment]
for now we are moving towards drag-and-drop on desktop only so lets table this

**Comment by jrop** [comment]
@joehand @karissa Is there a way to include hidden files, from the CLI?

**Comment by joehand** [comment]
@jrop yes, you can use the option `--include-hidden`
