### ISSUE TITLE
filename encoding for non-ascii broken in zip archive

### ISSUE THREAD

**Issue by clkao** [datproject/datfolder#277]
1. uploading 健保藥品使用量分析.csv to dat.land
2. observe filename display correctly in the webui
3. go to individual file view
4. download the archive

```
 unzip -l  ~/Downloads/健保藥品使用量分析.csv.zip
Archive:  /Users/chia-liang.kao/Downloads/健保藥品使用量分析.csv.zip
  Length     Date   Time    Name
 --------    ----   ----    ----
   268062  09-22-16 03:07   ����+��������+����������.csv
 --------                   -------
   268062                   1 file
```

**Comment by juliangruber** [comment]
i've had one weird issue with hyperdrive and non utf8 characters before too, but unfortunately can't remember what it was exactly

**Comment by karissa** [comment]
At some point there's probably a toString on the filename... If we are getting these as strings from archive.list it might be in there.

**Comment by karissa** [comment]
I couldn't really reproduce this locally, but I did find a different bug that might be related -- see #284

**Comment by karissa** [comment]
Never was able to reproduce, can reopen if it comes back
