### ISSUE TITLE
[ops] automate releases

### ISSUE THREAD

**Issue by yoshuawuyts** [datproject/datfolder#318]
It'd be cool to use hyper tech to run our releases. All of this doesn't need to happen now, but I reckon it would be cool to incrementally build these things out as the more we use our own tech in production the more we'll find bugs and pain points and blaze the path for other folks to adopt it too.

I think these are the packages we need to build to make releases using hypertech happen:

- [x] __github-to-hypercore:__  [(repo)](https://github.com/yoshuawuyts/github-to-hypercore) get all `github` webhook events for a user / org and pipe them into a hypercore
- [ ] __github-releases-feed:__ take a `github-to-hypercore` feed and filter release events for a single repository - should probably pipe this into a `hyperdrive` archive as `rabin` chunking could be leveraged to diff the tarballs which is like a cool thing. Any metadata we could store as an extra JSON file in the archive or something
- [ ] __hyperdrive-downloader:__ whenever a new version of the archive is released it downloads it to a directory. That's all. Each release has its own directory. Probably named by timestamp or tag or something. At this point we're then able to manually reboot `psy` to run the new code from the repo
- [ ] __psyperdrive:__ think `hyperdrive` + `psy` -  a new version of the archive is released it boots up a new process using psy and turns off the other one. Or the other way around. I haven't thought this one through too well yet, but that's fine b/c it's the last in line

cc/ @juliangruber @mafintosh you're the folks I've talked to about this - thoughts? Do we need tags or something in `hyperdrive` for this to work?

**Comment by juliangruber** [comment]
This sounds interesting, and it's very helpful that you laid out the steps already.

While an automatic process is great, deployments also often need manual interventions, as in "oh shit, my shit is on fire, need to roll back the release asap" or retry the deployment, etc. There's a bunch of manual tasks. Do you have a plan how manual intervention could work?

**Comment by sallespro** [comment]
@yoshuawuyts i do like the way you laid out the development of this tools.
i am sort of doing the same effort considering the necessary modules to do something like this :

```
salles @sallespro Nov 22 11:26
@mafintosh you might know https://www.indiegogo.com/projects/daplie-the-cloud-system-to-take-back-the-internet#/
picture a small SSD drive and the minimal hw to run "hyper connector"

salles @sallespro Nov 22 11:33
how can a user’s applications ( messengers, blog, pictures) store feeds of data into a hyperdrive made of a swarm of this HWs ?
and back to the collections of DATs discussion, how would it be able to keep this several data types searchable / browseable ?


```

**Comment by yoshuawuyts** [comment]
@juliangruber yeah, that and more fancy schedule stuff could be added to whatever `psyperdrive` turns out to be. Maybe it's even layers on top of that, not sure. The first step would be to get release versions down to machines and we can leave the reverting up to folks to run themselves.

**Comment by yoshuawuyts** [comment]
@sallespro I don't think what we got here would necessarily match your use case - perhaps running a single hyperdrive would suffice for what you're trying to do. I reckon a first step would be to start tinkering with things and seeing how far you get.

**Comment by karissa** [comment]
@clkao is using docker puppet and watchtower for this
