### ISSUE TITLE
https/ssl setup

### ISSUE THREAD

**Issue by karissa** [datproject/datfolder#353]
- deploy this repo to beta.datproject.org until we launch
- get certs for datproject.org and beta.datproject.org
- automate letsencrypt (@clkao)
- add dns (@joehand)

**Comment by clkao** [comment]
deploy on beta.datproject.org, using https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion

**Comment by karissa** [comment]
OK All you @clkao !

**Comment by maxogden** [comment]
@clkao we got @joehand to add a dns entry for beta.datproject.org, and @karissa merged all the website code into this repo, so lemme know if theres anything else blocking you from getting this app deployed

**Comment by clkao** [comment]
This is now automatically deployed from the [datproject/datfolder:beta](https://hub.docker.com/r/datproject/datfolder/tags/) tag on docker hub.
