### ISSUE TITLE
data backups

### ISSUE THREAD

**Issue by karissa** [datproject/datfolder#354]
We are using sqlite, so maybe digital ocean should have this covered if we just backup the droplet every day

**Comment by clkao** [comment]
The deployed service has data in ~/data/datfolder on the host, if we choose to do more fine-grained backups.

**Comment by clkao** [comment]
Backup for the beta database is configured through puppet.  (we can add similar configuration for released easily)

Until we sort out the google cloud service account issue, i am using my gcloud storage bucket.

**Comment by karissa** [comment]
thanks @clkao !
