### ISSUE TITLE
merge datproject static site into this

### ISSUE THREAD

**Issue by clkao** [datproject/datfolder#357]

**Comment by joehand** [comment]
Maybe it'd still be good to have the blog separate repo? May help us avoid some merge conflicts and branch/PR saturation.

**Comment by Kriesse** [comment]
+1 on moving the blog to a separate repo. i'd like to make some improvements on the blog anyway, would be helpful to not block other projects with that.

**Comment by karissa** [comment]
Yeah, sounds good. blog.datproject.org

**Comment by joehand** [comment]
Set up DNS for github -> blog.datproject.org, so we can add a CNAME to whatever the repo ends up being and should *just work*.
