### ISSUE TITLE
Update Icon on loading screen

### ISSUE THREAD

**Issue by Kriesse** [datproject/datfolder#363]
Let's not use sad face here 
![image](https://cloud.githubusercontent.com/assets/53684/21862676/276c0a30-d7ef-11e6-8f0b-9b7b492346c7.png)

**Comment by karissa** [comment]
this is related to #367, cause we could remove this screen for now. 

Maybe we can have a screenshot to dat desktop with a link to it? And keep the current view for when we implement the websocket proxy.

**Comment by karissa** [comment]
This is the new message ![screen shot 2017-01-12 at 5 47 15 pm](https://cloud.githubusercontent.com/assets/633012/21915642/197b79f4-d8f0-11e6-9547-025e1377d030.png)
