### ISSUE TITLE
create 5 real live example datasets

### ISSUE THREAD

**Issue by maxogden** [datproject/datfolder#368]
- datasets that are explanatory
- ideally they have visualizaton/websites that we can screenshot
- to feature on the dat homepage
- put them all into a bot that we persistently mirror
- 3 for homepage view, 5 for desktop app screenshot

**Comment by Kriesse** [comment]
from @maxogden:
> heres the first 3 example datasets https://gist.github.com/maxogden/7aea28e0c97e9c3fbbfe7593769cb30d

> the first one is done and seeding, the other 2 are downloading but those links will be where they are seeding

> if you google image search icesat-2 there are some cool images :)

**Comment by maxogden** [comment]
The Densho one and CA Civic Data one are the best working ones right now. The ICESAT and OSM ones are bigger and there are some perf issues @mafintosh and @joehand are looking into.

**Comment by karissa** [comment]
@maxogden let's get a different dataset in the meantime to replace the OSM one. We need at least 3 on the front page! ideas?
