### ISSUE TITLE
simple CLI to set up a beta account

### ISSUE THREAD

**Issue by maxogden** [datproject/datfolder#383]
similar to https://github.com/staticland/staticland/blob/master/cli.js but can be less polished for now

if i want you invite you to our beta, i as an admin would have some special token and some hacky way to set up an account for your email

one question though for @karissa, would this thing let us create an account and get a sort of 'invite link' to give to the beta user? or do we set them a temporary password? depends on what functionality they are going to be able to use first on datfolder and what UI is there for them to use i guess

**Comment by joehand** [comment]
I thought we were using the github repo whitelist for this? 

Once a user is on the whitelist they can use the register command in the dat-next CLI and set their own username/password.

**Comment by karissa** [comment]
Good point @joehand, yeah we could just tell them to register.
